on:
  workflow_dispatch:

name: Test-Fortify
jobs:
  ci:
    runs-on: ubuntu-latest
    steps: 
      - name: Check-out source code
        uses: actions/checkout@v2
  
      - name: Check fortify
        run: echo "$(which FoDUpload)" && echo "FoDUpload found on path" && echo "$(which scancentral)" && echo "scancentral found on path" && echo "$(which FortifyVulnerabilityExporter)" && echo "FortifyVulnerabilityExporter found on path"
