name: test workflow
on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    env:
      ENV_CVP_DEPLOY_NUMBER: "cvp-common-service-$(date +%Y%m%d)"
    name: A job to say hello
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Check resule
        shell: bash
        run: cd deployment/tt && chmod +x check-deploy-result.sh && ./check-deploy-result.sh

      - name: Check File
        shell: bash
        run: |
          if [ ! -f "deploy-result-app31.txt" ]; then
            echo "deploy-result-app31.txt not exists"
          fi
          if [ ! -f "deploy-result-app32.txt" ]; then
            echo "deploy-result-app32.txt not exists"
          fi
          echo "ENV_CVP_DEPLOY_NUMBER=${{ env.ENV_CVP_DEPLOY_NUMBER }}"
